# @copyright Copyright (c) 2013-2016, Norwegian Defence Research Establishment (FFI) - All Rights Reserved
# @license Proprietary and confidential
# @author Arild Bergh/Sinett 3.0 programme (firstname.lastname@ffi.no)
# 
# Unauthorized copying of this file, via any medium is strictly prohibited 
# 
# For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: "@SinettMLABBuilderBundle/Resources/config/services.yml" }
    
framework:
    #esi:             ~
    translator:      { fallback: nb_NO }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['php', 'twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        mlab_variables: %mlab%
        supported_locales: %supported_locales%
        locale: %locale%
#    form:
#        resources:
#            - 'SinettMLABBuilderBundle:Form:selectElement.html.twig'

# Assetic Configuration
assetic:
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: /usr/bin/uglifyjs
            mangle: true
            compress: true
    debug:          %kernel.debug%
    bundles: [ SinettMLABBuilderBundle, FOSUserBundle ]
            
    assets:
#        common_jquery_js:
#            inputs:
#                - '@SinettMLABBuilderBundle/Resources/public/js/jquery-2.1.4.js'
#                - '@SinettMLABBuilderBundle/Resources/public/js/jquery.ui-1.11.4.js'
#                - '@SinettMLABBuilderBundle/Resources/public/js/jquery.uploadfile-4.0.11.js'
#                - '@SinettMLABBuilderBundle/Resources/public/js/jquery.qtip-2.2.0.js'
#                - '@SinettMLABBuilderBundle/Resources/public/js/bowser.js'
#                
#        applist_mlab_js:
#            inputs:
#                - '@SinettMLABBuilderBundle/Resources/public/js/jquery.ddslick-1.0.0.js'
#                - '@SinettMLABBuilderBundle/Resources/public/js/jquery.contextmenu.js'
#                
#        editor_jquery_js:
#            inputs:
#                - '@SinettMLABBuilderBundle/Resources/public/js/jquery.mobile-1.4.5.js'
#                - '@SinettMLABBuilderBundle/Resources/public/js/jquery.ddslick-1.0.0.js'
#                - '@SinettMLABBuilderBundle/Resources/public/js/jquery.qrcode-0.12.0.js'
#                - '@SinettMLABBuilderBundle/Resources/public/js/spin.js'
#                - '@SinettMLABBuilderBundle/Resources/public/js/jquery.spin.js'
        
        editor_mlab_js:
            inputs:
                - '@SinettMLABBuilderBundle/Resources/public/js/mlab.api.js'
                - '@SinettMLABBuilderBundle/Resources/public/js/mlab.dt.api.js'
                - '@SinettMLABBuilderBundle/Resources/public/js/mlab.dt.management.js'
                - '@SinettMLABBuilderBundle/Resources/public/js/mlab.dt.bestpractice.js'
                - '@SinettMLABBuilderBundle/Resources/public/js/mlab.dt.design.js'
                - '@SinettMLABBuilderBundle/Resources/public/js/mlab.dt.utils.js'
                - '@SinettMLABBuilderBundle/Resources/public/js/mlab_editor.init.js'
                
#        common_jquery_css:
#            inputs:
#                - '@SinettMLABBuilderBundle/Resources/public/css/jquery-ui.css'
#                - '@SinettMLABBuilderBundle/Resources/public/css/jquery-qtip.css'
#                - '@SinettMLABBuilderBundle/Resources/public/css/jquery.uploadfile.css'
#                - '@SinettMLABBuilderBundle/Resources/public/css/jquery.contextmenu.css'
#                
#        general_mlab_css:
#            inputs:
#                - '@SinettMLABBuilderBundle/Resources/public/css/mlab_menu.css'
#                - '@SinettMLABBuilderBundle/Resources/public/css/mlab_all.css'
#
#        editor_mlab_css:
#            inputs:
#                - '@SinettMLABBuilderBundle/Resources/public/css/mlab_reset_editor.css'
#                - '@SinettMLABBuilderBundle/Resources/public/css/mlab_menu.css'
#                - '@SinettMLABBuilderBundle/Resources/public/css/mlab_editor.css'
#                - '@SinettMLABBuilderBundle/Resources/public/css/mlab_component_config.css'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# FOS user bundle configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Sinett\MLAB\BuilderBundle\Entity\User
    group:
        group_class: Sinett\MLAB\BuilderBundle\Entity\Group
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

# additional services
services:
    security.authentication.customized_success_handler:
        class: %security.authentication.success_handler.class%
        public: false
        arguments:  ['@router', '@security.authorization_checker', '@service_container']
        
    sinett_mlab_builder.locale_listener:
        class: Sinett\MLAB\BuilderBundle\Listener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }
            
    sinett_mlab_builder.user_locale_listener:
        class: Sinett\MLAB\BuilderBundle\Listener\UserLocaleListener
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
            
# these Mlab parameters are generic to the Mlab app and not dependent on the server installations.
# Typically they are here so they can be changed without changing code in the app when, for instance, new converters are installed, etc.

parameters:
    supported_locales: {en_GB: 'English', nb_NO: 'Norsk'}
    security.authentication.success_handler.class: Sinett\MLAB\BuilderBundle\Handler\AuthenticationSuccessHandler
    mlab_app: 
        missing_icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAEbgAABG4B0KOyaAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAD4SURBVDiNpdO9LoRREMbx3/iqRaKREIVCoVETlmoLiauwjbgAvWvQqH1cgyhU3IBCoVJoZBUiFMIo9hSb17vvZplkknPm43+emeRAB13kiN5FJ8rhBNdGsxb2FFo7M/U7VnGAQ2wjKvl26f0NwFGJf+OznM8xORSAjRK7wwJmcVtiO1XAWM1sK3jHfmY+ZuYzrkpuuW4ZVQWBub77Gl7xhqWhCrJnTxARm7gs0N3MfKjWT9RJ6rPjUrOVmTd1BXU7UF4PzONiUHOjgszMiFjHfZPEJgVTOMPpnwAYxzRmmgBNI3xExCK+hgFe0OrtrN4G5Fql93/f+QdOZKfScs6QZgAAAABJRU5ErkJggg==
        save_interval: 60
        icon_text_maxlength: 6

        convert:
            converter_bin: document2HTML.py
            config: config.json
            converter_path: ../src/Sinett/MLAB/BuilderBundle/FileManagement/conv/
            filetype_allowed: [application/msword, application/vnd.ms-powerpoint, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.openxmlformats-officedocument.presentationml.presentation]

        ws_socket:
            path_client: /messages/
            path_server: /messages/

        uploads_allowed:
          image: [image/gif, image/jpeg, image/png]
          video: [video/webm, video/mp4, video/ogg, video/x-msvideo, video/3gpp, video/quicktime]
          audio: [audio/mp4, audio/mpeg3, audio/mpeg, audio/wave, audio/x-wav, audio/wav, audio/aac, audio/webm, audio/ogg]
          
        filenames:
          component_icon: icon.png
          app_icon: icon.png
          app_splash_screen: splash
          app_config: conf.json
        
        compiler_service:
            default_icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAB31JREFUeNrUWgtsk1UU/tputGxsbgtj1PDYAycDVodMERUBFYQgBB9M5gs2k5KhETHGTEOMEhTjC1DjskZhOFBBAhp8EXU4RTbneIhxbMuAblAKbGu7R9fX3//33H/dbNd2rI8VucnJ7X//x/2+c84993EqEQQB13KJCvUDbW1tiIqKgkwmE2upVNr/W6PRZNMjTrVaXed0OsGUxWp3SUhICKl/6XBoZdu2bUkEfktSUtLJxMTEf+j3u4zUcBRJqC7kbgG5XI6ysrJVEolke05ODmbMmAGe51FdXY26urr99HhJQUHBjw6HI2wWCJlA7OMvivXmuyaNpGojAXp+7ty5GDNmjMdzWq0WlZWVsNls69f92vR6X7t551tXdwy4wD9CVZFKpZqTm5srWoSVPuWQRZCamork5GRUVFRs3HwXxlLzm0REN2wuRH77EQM1lI/ExcWBaV2pVIrXzDUYaCYendE16+/EiROora1FANYvoUCwxucd9hFfUlpaKrS3twuBFPJtwWq1ijWREKx2hyg0DgSO48T2QIvRaBQYFn84B3Wh5uZmnDt3rj809oXHvtpd3MMoKx//XI3ndx4Qf39Y8ACemD1D/E1jwCOMEjEvcb/PgsCwjwH3YjRb8M43v2D732dww0trITg5rNPsQuOFy9iQtzDsYTSs88DnR44j47k3sZcfiYlqAm+jseoch9SiddhxuQcFJV/g9wbt1ZuJP6ioxZdHT6Hbavd5Xz4mGWlrnkZ07Hg49B3gLWaxXRYbj5QFeahp+QtfbS0Hb7P77SPvlikoXjhreAh8WXsKY59eD/kEBSQDbCc4SdkdgKPdBrteD4Fz9N/jOg1wWs1QJKtw4ys3QRoLr/dZsV8E9rzx4vARYMWqbYZdNyJgUwuWHtgtWtgvXOXFHBuUgnRYllCRIkCrSqnzWiZwrVuAd4okQinRUgmWpSXBSTPpDy0m9HB8BBdzNFMKkIQEfssd6VgwIVG8Xk5EVhysj6QLUXiUBA9+6+zMfvCsTE+O7f1mxAhwzH0CZyCjlejmOZMJfJJH+2GdyfXNiBLwLIooKWYqExETLcP3Zy77BP/+/KlYlDbao732oglrDp6kbzojOYiJgFt/cSOicGD5rUi9Lka8Lj2uxaYjjR7gt8zPxqJ0zx3an3oTVh04CrPDGeEoxJYIbhuRacr4fvCsrJ6eimiJgNcq63rBL8zB/TeM9QR/wYDH99fAyoU+nwRBgDp120jVkxu0mm1IjpX3txXmpEFKzyQoorEk83pP8Lp2PLa3KizggyLAkwUkwn9xu7XLgYc/+wW7V9BGN25kf/uq6Wle79acb8Oju38LG/ig9gPiTMx5StNlIx4q/xkXuyx+36s514r8XYdgsdq83neXCBBw+JSzbUYs2/4DdB1mr3eqmi9hRfmPsNisft/vk+EnQOb3p73mNhMe3Pa9B4kq7UU8+unBK2o+IhaQU5wXOPugGmxuM2Cp5mu0GLtQdVaP/LLvCPyVNc+E52yIGRHtffZD0Uyj0chCHsRTlKPxp6EHUYqRgz53niyxtGQfjD02WB1D16rTbkNGcqJPAoIgsE67A7GAgRtg0nk3poLr6e4dyFeQC4YOl+a5IQv79j1ZqZ5Rj+eZWNRqdXegLqRjh7DuZbFqEjjaGvKkqUCADUV4ck0HEcjLneK5T7aLBwC6YMbA4a6uLs/VpEyKF+67DbZOU+/OLIxi7+zA6jk3Y5TCc79tNosB4WgwBPYajUavxidvV+GxW7J6SXCOsGjf3t2JvJsz8ey9M70Pynox7A+YAPlcRWdnZ1V3t7frFS++EytnTYPd3N0b/kLQvKPHjBW5k/Hqsnle/VgsFhgMBlGZwYbREnY+6usUuXjxbKjJ5HbyW95BfkpbzUCEWY+9u/L2bGx48B6fnbe0tLC+nyNlOoNOcLBUkVKpXJuRkeHzcPdQvRa7jpxAZUMzZHQ98Ejd12k47zrA3bh8AZ64I8fn4a5Op0NTU5OGwK8OdTH3kl6vHxETE1M0btw4r5vzp03CopzJKK2owYZ9P/WfZA8k0pfgY2Hx5WV3Q333THGLyfmYfVtbW3H69GnRA4JOcAywAottz6SlpRWlp6f7PV7naatZfvgYth+qQYO+FVIXCZ76mDR2NJ6aNxOr5uTSPgF+j9fZcX59fT0jPJe0XxkWAi4SE5jrp6SkFE2dOhUKhcJvfoD9/q3+LPb9cRJO0viS3GlYoMr0mWZ1B08ug8bGxjJXRqYmpBTTIEQ2yeXyYpVKJaaU/BFgtbsbMdfxR8BkMuHYsWOsZi7zNoE/O1Q8QWUpicRSqorGjx+/kFkjPj4+KAIsW9PQ0CC6DF2zaLM1UCwhpVmJSDEB3cTGRXZ2NkaNGjUkAmx5wEDX1dUxEm/T7Q8JfEswGELOExMJNvcXE+jXJk6ciKysLNA48UmAuQrTOPN1q9X6nsvXm0LpP2yZ+j179rDlrpgvTkhIuJXNG0wYERYS2aR06dKlBrr/CUlZfn5+6/8iU+/rzx47duyY4iLDhFloN8m3hYWFh8P9Zw/Jtf53m38FGADbB2OE+c9o0gAAAABJRU5ErkJggg==
            config_uid_tag: widget
            config_uid_attribute: id
            app_uid_metatag_placeholder: %%%%APP_UID%%%%
            app_name_placeholder: %%%%APP_NAME%%%%
            file_extensions: {ios: 'ipa', android: 'apk'}
            rsync_suffix: /www/

# when a user is uploading a file these files have to be present to be accepted
        verify_uploads:
            template:
                - frontpage.html
                - page.html
                - thumbnail.jpg
                - conf.yml
                - js/jquery.js
                - js/jquery-ui.js
                - js/jquery-mobile.js
                - js/mlab.api.js
                - css/mlab_component.css
                - css/jquery-ui.css
                - css/jquery-mobile.css
            template_conf_required: [name, tooltip]
            component:
                - code_dt.js
                - conf.yml
                - icon.png
            component_conf_required: [category, html, name, tooltip]
            app:
                - www
            template_required_strings:
                frontpage.html: '/\<div .*id\=.mlab_editable_area.*?\>/'
            
        component_files: { ICON: icon.png, CONFIG: conf.yml, SCRIPTS: code_dt.js, PHP: server_code.php }
        
        app:
            copy_files: { frontpage.html: index.html, js/: js, css/: css, img/: img }
            new_page: page.html
            content_id: mlab_editable_area
#            html_header: <!DOCTYPE html>\n<html>\n<head><title>%%TITLE%%</title></head>\n<body>\n
#            html_footer: \n</body></html>
            html_header: <!DOCTYPE html>\n<html>\n<head>\n<title>%%TITLE%%</title>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />\n</head>\n<body>\n<div data-role="page" data-title="%%TITLE%%">\n<div class="mlab_content_wrapper">\n<div role="main" class="mlab_main_body_content">\n</div>\n</div>\n</div>
            html_footer: \n</body></html>

            
        replace_in_filenames: { a: '/[ÂÃÄÀÁÅàáâãäå]/', ae: '/[Ææ]/', c: '/[Çç]/', e: '/[ÈÉÊËèéêë]/', i: '/[ÌÍÎÏìíîï]/', o: '/[ÒÓÔÕÖØòóôõöø]/', n: '/[Ññ]/', u: '/[ÙÚÛÜùúûü]/', y: '/[Ýýÿ]/', _: '/[^A-Za-z0-9]/' }    

        plugins: ["cordova-plugin-device", "cordova-plugin-network-information"]
