# @copyright Copyright (c) 2013-2016, Norwegian Defence Research Establishment (FFI) - All Rights Reserved
# @license Proprietary and confidential
# @author Arild Bergh/Sinett 3.0 programme (firstname.lastname@ffi.no)
# 
# Unauthorized copying of this file, via any medium is strictly prohibited 
# 
# For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: "@SinettMLABBuilderBundle/Resources/config/services.yml" }
    
framework:
    #esi:             ~
    translator:      { fallback: nb_NO }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['php', 'twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        mlab_variables: %mlab%
        supported_locales: %supported_locales%
        locale: %locale%
#    form:
#        resources:
#            - 'SinettMLABBuilderBundle:Form:selectElement.html.twig'

# Assetic Configuration
assetic:
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: /usr/bin/uglifyjs
            mangle: true
            compress: true
    debug:          %kernel.debug%
    bundles: [ SinettMLABBuilderBundle, FOSUserBundle ]
            
    assets:
#        common_jquery_js:
#            inputs:
#                - '@SinettMLABBuilderBundle/Resources/public/js/jquery-2.1.4.js'
#                - '@SinettMLABBuilderBundle/Resources/public/js/jquery.ui-1.11.4.js'
#                - '@SinettMLABBuilderBundle/Resources/public/js/jquery.uploadfile-1.9.0.js'
#                - '@SinettMLABBuilderBundle/Resources/public/js/jquery.qtip-2.2.0.js'
#                - '@SinettMLABBuilderBundle/Resources/public/js/bowser.js'
#                
#        applist_mlab_js:
#            inputs:
#                - '@SinettMLABBuilderBundle/Resources/public/js/jquery.ddslick-1.0.0.js'
#                - '@SinettMLABBuilderBundle/Resources/public/js/jquery.contextmenu.js'
#                
#        editor_jquery_js:
#            inputs:
#                - '@SinettMLABBuilderBundle/Resources/public/js/jquery.mobile-1.4.5.js'
#                - '@SinettMLABBuilderBundle/Resources/public/js/jquery.ddslick-1.0.0.js'
#                - '@SinettMLABBuilderBundle/Resources/public/js/jquery.qrcode-0.12.0.js'
#                - '@SinettMLABBuilderBundle/Resources/public/js/spin.js'
#                - '@SinettMLABBuilderBundle/Resources/public/js/jquery.spin.js'
        
        editor_mlab_js:
            inputs:
                - '@SinettMLABBuilderBundle/Resources/public/js/mlab.api.js'
                - '@SinettMLABBuilderBundle/Resources/public/js/mlab.dt.api.js'
                - '@SinettMLABBuilderBundle/Resources/public/js/mlab.dt.management.js'
                - '@SinettMLABBuilderBundle/Resources/public/js/mlab.dt.bestpractice.js'
                - '@SinettMLABBuilderBundle/Resources/public/js/mlab.dt.design.js'
                - '@SinettMLABBuilderBundle/Resources/public/js/mlab.dt.utils.js'
                - '@SinettMLABBuilderBundle/Resources/public/js/mlab_editor.init.js'
                
#        common_jquery_css:
#            inputs:
#                - '@SinettMLABBuilderBundle/Resources/public/css/jquery-ui.css'
#                - '@SinettMLABBuilderBundle/Resources/public/css/jquery-qtip.css'
#                - '@SinettMLABBuilderBundle/Resources/public/css/jquery.uploadfile.css'
#                - '@SinettMLABBuilderBundle/Resources/public/css/jquery.contextmenu.css'
#                
#        general_mlab_css:
#            inputs:
#                - '@SinettMLABBuilderBundle/Resources/public/css/mlab_menu.css'
#                - '@SinettMLABBuilderBundle/Resources/public/css/mlab_all.css'
#
#        editor_mlab_css:
#            inputs:
#                - '@SinettMLABBuilderBundle/Resources/public/css/mlab_reset_editor.css'
#                - '@SinettMLABBuilderBundle/Resources/public/css/mlab_menu.css'
#                - '@SinettMLABBuilderBundle/Resources/public/css/mlab_editor.css'
#                - '@SinettMLABBuilderBundle/Resources/public/css/mlab_component_config.css'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# FOS user bundle configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Sinett\MLAB\BuilderBundle\Entity\User
    group:
        group_class: Sinett\MLAB\BuilderBundle\Entity\Group

# additional services
services:
    security.authentication.customized_success_handler:
        class: %security.authentication.success_handler.class%
        public: false
        arguments:  ['@router', '@security.authorization_checker', '@service_container']
        
    sinett_mlab_builder.locale_listener:
        class: Sinett\MLAB\BuilderBundle\Listener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }
            
    sinett_mlab_builder.user_locale_listener:
        class: Sinett\MLAB\BuilderBundle\Listener\UserLocaleListener
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
            