# @copyright Copyright (c) 2013-2016, Norwegian Defence Research Establishment (FFI) - All Rights Reserved
# @license Proprietary and confidential
# @author Arild Bergh/Sinett 3.0 programme (firstname.lastname@ffi.no)
# 
# Unauthorized copying of this file, via any medium is strictly prohibited 
# 
# For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                success_handler: security.authentication.customized_success_handler
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/callback/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/category/.+/.+/load_categories, role: ROLE_USER }
        - { path: ^/category/, role: ROLE_ADMIN }
        - { path: ^/component/, role: ROLE_ADMIN }
        - { path: ^/componentgroup/, role: ROLE_ADMIN }
        - { path: ^/group/, role: ROLE_ADMIN }
        - { path: ^/menu/, role: ROLE_ADMIN }
        - { path: ^/template/, role: ROLE_ADMIN }
        - { path: ^/tracking/, role: ROLE_ADMIN }
        - { path: ^/user/, role: ROLE_ADMIN }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/system, role: ROLE_SUPER_ADMIN }
        - { path: ^/system/, role: ROLE_SUPER_ADMIN }
        - { path: ^/app/, role: ROLE_USER }


        