security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/app/, role: ROLE_USER }
        - { path: ^/category/, role: ROLE_USER }
        - { path: ^/component/, role: ROLE_USER }
        - { path: ^/group/, role: ROLE_USER }
        - { path: ^/menu/, role: ROLE_USER }
        - { path: ^/template/, role: ROLE_USER }
        - { path: ^/tracking/, role: ROLE_USER }
        - { path: ^/user/, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/system, role: ROLE_SUPER_ADMIN }
        - { path: ^/system/, role: ROLE_SUPER_ADMIN }

        