app:
    pattern:  /
    defaults: { _controller: "SinettMLABBuilderBundle:App:index" }

app_show:
    pattern:  /{id}/show
    defaults: { _controller: "SinettMLABBuilderBundle:App:show" }

app_new:
    pattern:  /new
    defaults: { _controller: "SinettMLABBuilderBundle:App:new" }

app_create:
    pattern:  /create
    defaults: { _controller: "SinettMLABBuilderBundle:App:create" }
    requirements: { _method: post }

app_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SinettMLABBuilderBundle:App:edit" }

app_update:
    pattern:  /{id}/update
    defaults: { _controller: "SinettMLABBuilderBundle:App:update" }
    requirements: { _method: post|put }

app_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SinettMLABBuilderBundle:App:delete" }

app_remove_from_appstore:
    pattern:  /{id}/removeAppStore
    defaults: { _controller: "SinettMLABBuilderBundle:App:removeAppStore" }

app_recall:
    pattern:  /{id}/recall
    defaults: { _controller: "SinettMLABBuilderBundle:App:recall" }

app_builder_index:
    path:   /builder/
    defaults: { _controller: "SinettMLABBuilderBundle:App:builder" }

app_builder_editor:
    path:   /builder/{id}/{page_num}/build
    defaults: { _controller: "SinettMLABBuilderBundle:App:buildApp" }

app_builder_page_get:
    path:   /builder/{app_id}/{page_num}/{uid}/page_get
    defaults: { _controller: "SinettMLABBuilderBundle:App:getPage" }

app_builder_editor_closed:
    path:   /builder/{uid}/editor_closed
    defaults: { _controller: "SinettMLABBuilderBundle:App:closeEditor" }

app_builder_page_save:
    path:   /builder/{app_id}/{page_num}/page_put
    defaults: { _controller: "SinettMLABBuilderBundle:App:putPage" }
    requirements: { _method: post }

app_builder_page_new:
    path:   /builder/{app_id}/page_new
    defaults: { _controller: "SinettMLABBuilderBundle:App:newPage" }
    requirements: { _method: post }

app_builder_page_copy:
    path:   /builder/{app_id}/{page_num}/page_copy
    defaults: { _controller: "SinettMLABBuilderBundle:App:copyPage" }

app_builder_page_delete:
    path:   /builder/{app_id}/{page_num}/{uid}/page_delete
    defaults: { _controller: "SinettMLABBuilderBundle:App:deletePage" }
    
app_builder_app_unlock:
    path:   /builder/app_removelocks
    defaults: { _controller: "SinettMLABBuilderBundle:App:removeLocks" }
    
app_builder_app_download:
    path:   /builder/{app_id}/download
    defaults: { _controller: "SinettMLABBuilderBundle:App:downloadApp" }

app_builder_copy_app:
    path:   /builder/{id}/copy
    defaults: { _controller: "SinettMLABBuilderBundle:App:copyApp" }

app_builder_component_added:
    path:   /builder/{app_id}/{comp_id}/component_added
    defaults: { _controller: "SinettMLABBuilderBundle:App:componentAdded" }

app_builder_component_upload:
    path:   /builder/{app_id}/{comp_id}/component_upload
    defaults: { _controller: "SinettMLABBuilderBundle:App:componentUpload" }
    requirements: { _method: post }

