app:
    pattern:  /
    defaults: { _controller: "SinettMLABBuilderBundle:App:index" }

app_show:
    pattern:  /{id}/show
    defaults: { _controller: "SinettMLABBuilderBundle:App:show" }

app_new:
    pattern:  /new
    defaults: { _controller: "SinettMLABBuilderBundle:App:new" }

app_create:
    pattern:  /create
    defaults: { _controller: "SinettMLABBuilderBundle:App:create" }
    requirements: { _method: post }

app_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SinettMLABBuilderBundle:App:edit" }

app_update:
    pattern:  /{id}/update
    defaults: { _controller: "SinettMLABBuilderBundle:App:update" }
    requirements: { _method: post|put }

app_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SinettMLABBuilderBundle:App:delete" }
    requirements: { _method: post|delete }
