app:
    pattern:  /
    defaults: { _controller: "SinettMLABBuilderBundle:App:index" }

app_show:
    pattern:  /{id}/show
    defaults: { _controller: "SinettMLABBuilderBundle:App:show" }

app_new:
    pattern:  /new
    defaults: { _controller: "SinettMLABBuilderBundle:App:new" }

app_create:
    pattern:  /create
    defaults: { _controller: "SinettMLABBuilderBundle:App:create" }
    requirements: { _method: post }

app_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SinettMLABBuilderBundle:App:edit" }

app_update:
    pattern:  /{id}/update
    defaults: { _controller: "SinettMLABBuilderBundle:App:update" }
    requirements: { _method: post|put }

app_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SinettMLABBuilderBundle:App:delete" }

app_remove_from_appstore:
    pattern:  /{id}/removeAppStore
    defaults: { _controller: "SinettMLABBuilderBundle:App:removeAppStore" }

app_recall:
    pattern:  /{id}/recall
    defaults: { _controller: "SinettMLABBuilderBundle:App:recall" }

app_builder_index:
    path:   /builder/
    defaults: { _controller: "SinettMLABBuilderBundle:App:builder" }

app_builder_editor:
    path:   /builder/{id}/{version}/{page_num}/build
    defaults: { _controller: "SinettMLABBuilderBundle:App:buildApp" }

app_builder_copy_app:
    path:   /builder/{id}/{version}/copy
    defaults: { _controller: "SinettMLABBuilderBundle:App:copyApp" }

