# @copyright Copyright (c) 2013-2016, Norwegian Defence Research Establishment (FFI) - All Rights Reserved
# @license Proprietary and confidential
# @author Arild Bergh/Sinett 3.0 programme (firstname.lastname@ffi.no)
# 
# Unauthorized copying of this file, via any medium is strictly prohibited 
# 
# For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.
category:
    path:  /
    defaults: { _controller: "SinettMLABBuilderBundle:Category:index" }

category_show:
    path:  /{id}/show
    defaults: { _controller: "SinettMLABBuilderBundle:Category:show" }

category_new:
    path:  /{id}/new
    defaults: { _controller: "SinettMLABBuilderBundle:Category:new" }

category_create:
    path:  /create
    defaults: { _controller: "SinettMLABBuilderBundle:Category:create" }
    requirements: { methods: post }

category_edit:
    path:  /{id}/edit
    defaults: { _controller: "SinettMLABBuilderBundle:Category:edit" }

category_update:
    path:  /{id}/update
    defaults: { _controller: "SinettMLABBuilderBundle:Category:update" }
    requirements: { methods: post|put }

category_delete:
    path:  /{id}/delete
    defaults: { _controller: "SinettMLABBuilderBundle:Category:delete" }
#    requirements: { methods: post|delete }
    
category_load_categories:
    path:  /{id}/{level}/load_categories
    defaults: { _controller: "SinettMLABBuilderBundle:Category:loadCategories" }