componentgroup:
    path:     /
    defaults: { _controller: "SinettMLABBuilderBundle:ComponentGroup:index" }

componentgroup_show:
    path:     /{id}/show
    defaults: { _controller: "SinettMLABBuilderBundle:ComponentGroup:show" }

componentgroup_new:
    path:     /new
    defaults: { _controller: "SinettMLABBuilderBundle:ComponentGroup:new" }

componentgroup_create:
    path:     /create
    defaults: { _controller: "SinettMLABBuilderBundle:ComponentGroup:create" }
    requirements: { _method: post }

componentgroup_edit:
    path:     /{component_id}/edit
    defaults: { _controller: "SinettMLABBuilderBundle:ComponentGroup:edit" }

componentgroup_update_groups:
    path:     /{component_id}/update_groups
    defaults: { _controller: "SinettMLABBuilderBundle:ComponentGroup:updateGroups" }
    requirements: { _method: post|put }

componentgroup_admin_new:
    path:     /{component_id}/admin_new
    defaults: { _controller: "SinettMLABBuilderBundle:ComponentGroup:adminNew" }
    
componentgroup_update:
    path:     /{id}/update
    defaults: { _controller: "SinettMLABBuilderBundle:ComponentGroup:update" }
    requirements: { _method: post|put }

componentgroup_delete:
    path:     /{id}/delete
    defaults: { _controller: "SinettMLABBuilderBundle:ComponentGroup:delete" }
    requirements: { _method: post|delete }