# @copyright Copyright (c) 2013-2016, Norwegian Defence Research Establishment (FFI) - All Rights Reserved
# @license Proprietary and confidential
# @author Cecilie Jackbo Gran/Sinett 3.0 programme (firstname.middlename.lastname@ffi.no)
# 
# Unauthorized copying of this file, via any medium is strictly prohibited 
# 
# For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.
componentgroup:
    path:     /
    defaults: { _controller: "SinettMLABBuilderBundle:ComponentGroup:index" }

componentgroup_show:
    path:     /{id}/show
    defaults: { _controller: "SinettMLABBuilderBundle:ComponentGroup:show" }

componentgroup_new:
    path:     /new
    defaults: { _controller: "SinettMLABBuilderBundle:ComponentGroup:new" }

componentgroup_create:
    path:     /create
    defaults: { _controller: "SinettMLABBuilderBundle:ComponentGroup:create" }
    requirements: { methods: post }

componentgroup_edit:
    path:     /{component_id}/edit
    defaults: { _controller: "SinettMLABBuilderBundle:ComponentGroup:edit" }

componentgroup_update_groups:
    path:     /{component_id}/update_groups
    defaults: { _controller: "SinettMLABBuilderBundle:ComponentGroup:updateGroups" }
    requirements: { methods: post|put }

componentgroup_admin_new:
    path:     /{component_id}/admin_new
    defaults: { _controller: "SinettMLABBuilderBundle:ComponentGroup:adminNew" }
    
componentgroup_update:
    path:     /{id}/update
    defaults: { _controller: "SinettMLABBuilderBundle:ComponentGroup:update" }
    requirements: { methods: post|put }

componentgroup_delete:
    path:     /{id}/delete
    defaults: { _controller: "SinettMLABBuilderBundle:ComponentGroup:delete" }
    requirements: { methods: post|delete }