component:
    path:  /
    defaults: { _controller: "SinettMLABBuilderBundle:Component:index" }

component_show:
    path:  /{id}/show
    defaults: { _controller: "SinettMLABBuilderBundle:Component:show" }

component_new:
    path:  /new
    defaults: { _controller: "SinettMLABBuilderBundle:Component:new" }

component_create:
    path:  /create
    defaults: { _controller: "SinettMLABBuilderBundle:Component:create" }
    requirements: { methods: post }

component_edit:
    path:  /{id}/edit
    defaults: { _controller: "SinettMLABBuilderBundle:Component:edit" }

component_update:
    path:  /{id}/update
    defaults: { _controller: "SinettMLABBuilderBundle:Component:update" }
    requirements: { methods: post|put }

component_delete:
    path:  /{id}/delete
    defaults: { _controller: "SinettMLABBuilderBundle:Component:delete" }

component_toggle_state:
    path:  /{id}/toggle_state
    defaults: { _controller: "SinettMLABBuilderBundle:Component:toggleState" }
