# @copyright Copyright (c) 2013-2020, Norwegian Defence Research Establishment (FFI)
# @license Licensed under the Apache License, Version 2.0 (For the full copyright and license information, please view the /LICENSE_MLAB file that was distributed with this source code)
# @author Arild Bergh/Sinett 3.0 programme (firstname.lastname@ffi.no)
# 
 
# For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.
group:
    path:  /
    defaults: { _controller: "SinettMLABBuilderBundle:Group:index" }

group_show:
    path:  /{id}/show
    defaults: { _controller: "SinettMLABBuilderBundle:Group:show" }

group_new:
    path:  /new
    defaults: { _controller: "SinettMLABBuilderBundle:Group:new" }

group_create:
    path:  /create
    defaults: { _controller: "SinettMLABBuilderBundle:Group:create" }
    requirements: { methods: post }

group_edit:
    path:  /{id}/edit
    defaults: { _controller: "SinettMLABBuilderBundle:Group:edit" }

group_update:
    path:  /{id}/update
    defaults: { _controller: "SinettMLABBuilderBundle:Group:update" }
    requirements: { methods: post|put }

group_delete:
    path:  /{id}/delete
    defaults: { _controller: "SinettMLABBuilderBundle:Group:delete" }
#    requirements: { methods: post|delete }

group_toggle_state:
    path:  /{id}/toggle_state
    defaults: { _controller: "SinettMLABBuilderBundle:Group:toggleState" }