help:
    pattern:  /
    defaults: { _controller: "SinettMLABBuilderBundle:Help:index" }

help_show:
    pattern:  /{id}/show
    defaults: { _controller: "SinettMLABBuilderBundle:Help:show" }

help_new:
    pattern:  /new
    defaults: { _controller: "SinettMLABBuilderBundle:Help:new" }

help_create:
    pattern:  /create
    defaults: { _controller: "SinettMLABBuilderBundle:Help:create" }
    requirements: { _method: post }

help_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SinettMLABBuilderBundle:Help:edit" }

help_update:
    pattern:  /{id}/update
    defaults: { _controller: "SinettMLABBuilderBundle:Help:update" }
    requirements: { _method: post|put }

help_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SinettMLABBuilderBundle:Help:delete" }
    requirements: { _method: post|delete }
