# @copyright Copyright (c) 2013-2016, Norwegian Defence Research Establishment (FFI) - All Rights Reserved
# @license Proprietary and confidential
# @author Arild Bergh/Sinett 3.0 programme (firstname.lastname@ffi.no)
# 
# Unauthorized copying of this file, via any medium is strictly prohibited 
# 
# For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.
help:
    path:  /
    defaults: { _controller: "SinettMLABBuilderBundle:Help:index" }

help_show:
    path:  /{id}/show
    defaults: { _controller: "SinettMLABBuilderBundle:Help:show" }

help_new:
    path:  /new
    defaults: { _controller: "SinettMLABBuilderBundle:Help:new" }

help_create:
    path:  /create
    defaults: { _controller: "SinettMLABBuilderBundle:Help:create" }
    requirements: { methods: post }

help_edit:
    path:  /{id}/edit
    defaults: { _controller: "SinettMLABBuilderBundle:Help:edit" }

help_update:
    path:  /{id}/update
    defaults: { _controller: "SinettMLABBuilderBundle:Help:update" }
    requirements: { methods: post|put }

help_delete:
    path:  /{id}/delete
    defaults: { _controller: "SinettMLABBuilderBundle:Help:delete" }
#    requirements: { methods: post|delete }

help_getHtml:
    path:  /{route}/get_html
    defaults: { _controller: "SinettMLABBuilderBundle:Help:getHtml" }
    
help_get_component_helpfile:
    path:  /{comp_id}/get_component_helpfile
    defaults: { _controller: "SinettMLABBuilderBundle:Help:getComponentHelpfile" }
