menu:
    path:  /
    defaults: { _controller: "SinettMLABBuilderBundle:Menu:index" }

menu_show:
    path:  /{id}/show
    defaults: { _controller: "SinettMLABBuilderBundle:Menu:show" }

menu_new:
    path:  /new
    defaults: { _controller: "SinettMLABBuilderBundle:Menu:new" }

menu_create:
    path:  /create
    defaults: { _controller: "SinettMLABBuilderBundle:Menu:create" }
    requirements: { methods: post }

menu_edit:
    path:  /{id}/edit
    defaults: { _controller: "SinettMLABBuilderBundle:Menu:edit" }

menu_update:
    path:  /{id}/update
    defaults: { _controller: "SinettMLABBuilderBundle:Menu:update" }
    requirements: { methods: post|put }

menu_delete:
    path:  /{id}/delete
    defaults: { _controller: "SinettMLABBuilderBundle:Menu:delete" }
#    requirements: { methods: post|delete }
