template:
    path:  /
    defaults: { _controller: "SinettMLABBuilderBundle:Template:index" }

template_show:
    path:  /{id}/show
    defaults: { _controller: "SinettMLABBuilderBundle:Template:show" }

template_new:
    path:  /new
    defaults: { _controller: "SinettMLABBuilderBundle:Template:new" }

template_create:
    path:  /create
    defaults: { _controller: "SinettMLABBuilderBundle:Template:create" }
    requirements: { methods: post }

template_edit:
    path:  /{id}/edit
    defaults: { _controller: "SinettMLABBuilderBundle:Template:edit" }

template_update:
    path:  /{id}/update
    defaults: { _controller: "SinettMLABBuilderBundle:Template:update" }
    requirements: { methods: post|put }

template_delete:
    path:  /{id}/delete
    defaults: { _controller: "SinettMLABBuilderBundle:Template:delete" }

template_toggle_state:
    path:  /{id}/toggle_state
    defaults: { _controller: "SinettMLABBuilderBundle:Template:toggleState" }
