# @copyright Copyright (c) 2013-2020, Norwegian Defence Research Establishment (FFI)
# @license Licensed under the Apache License, Version 2.0 (For the full copyright and license information, please view the /LICENSE_MLAB file that was distributed with this source code)
# @author Arild Bergh/Sinett 3.0 programme (firstname.lastname@ffi.no)
# 
 
# For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.
template:
    path:  /
    defaults: { _controller: "SinettMLABBuilderBundle:Template:index" }

template_show:
    path:  /{id}/show
    defaults: { _controller: "SinettMLABBuilderBundle:Template:show" }

template_new:
    path:  /new
    defaults: { _controller: "SinettMLABBuilderBundle:Template:new" }

template_create:
    path:  /create
    defaults: { _controller: "SinettMLABBuilderBundle:Template:create" }
    requirements: { methods: post }

template_edit:
    path:  /{id}/{access}/edit
    defaults: { _controller: "SinettMLABBuilderBundle:Template:edit" }

template_update:
    path:  /{id}/update
    defaults: { _controller: "SinettMLABBuilderBundle:Template:update" }
    requirements: { methods: post|put }

template_update_group:
    path:  /{template_id}/{access}/update_groups
    defaults: { _controller: "SinettMLABBuilderBundle:Template:updateGroups" }
    requirements: { methods: post|put }

template_delete:
    path:  /{id}/delete
    defaults: { _controller: "SinettMLABBuilderBundle:Template:delete" }

template_toggle_state:
    path:  /{id}/toggle_state
    defaults: { _controller: "SinettMLABBuilderBundle:Template:toggleState" }
