# @copyright Copyright (c) 2013-2020, Norwegian Defence Research Establishment (FFI)
# @license Licensed under the Apache License, Version 2.0 (For the full copyright and license information, please view the /LICENSE_MLAB file that was distributed with this source code)
# @author Arild Bergh/Sinett 3.0 programme (firstname.lastname@ffi.no)
# 
 
# For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.
tracking:
    path:  /
    defaults: { _controller: "SinettMLABBuilderBundle:Tracking:index" }

tracking_show:
    path:  /{id}/show
    defaults: { _controller: "SinettMLABBuilderBundle:Tracking:show" }

tracking_new:
    path:  /new
    defaults: { _controller: "SinettMLABBuilderBundle:Tracking:new" }

tracking_create:
    path:  /create
    defaults: { _controller: "SinettMLABBuilderBundle:Tracking:create" }
    requirements: { methods: post }

tracking_edit:
    path:  /{id}/edit
    defaults: { _controller: "SinettMLABBuilderBundle:Tracking:edit" }

tracking_update:
    path:  /{id}/update
    defaults: { _controller: "SinettMLABBuilderBundle:Tracking:update" }
    requirements: { methods: post|put }

tracking_delete:
    path:  /{id}/delete
    defaults: { _controller: "SinettMLABBuilderBundle:Tracking:delete" }
#    requirements: { methods: post|delete }
