<?php
//This should be edited when Mlab or a lirbary is updated

$php_version_min = 50400; 
$php_version_max = 60000;
$mysql_version_min = 5.5;
$composer_version_min = 1.3;
$symfony_version_min = 2.8;
$uglifyjs_version_min = 2.4;
$nodejs_version_min = "0.10.29";
$system_path = "PATH='/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'";
$optional_params = array("parameters__database_port", "parameters__mailer_user", "parameters__mailer_password");
