# @copyright Copyright (c) 2013-2016, Norwegian Defence Research Establishment (FFI) - All Rights Reserved
# @license Proprietary and confidential
# @author Arild Bergh/Sinett 3.0 programme (firstname.lastname@ffi.no)
# 
# Unauthorized copying of this file, via any medium is strictly prohibited 
# 
# For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.

sinett_mlab_builder_homepage:
    path:  /
    defaults: { _controller: SinettMLABBuilderBundle:Default:index }

SinettMLABBuilderBundle_app:
    resource: "@SinettMLABBuilderBundle/Resources/config/routing/app.yml"
    prefix:   /app

SinettMLABBuilderBundle_component:
    resource: "@SinettMLABBuilderBundle/Resources/config/routing/component.yml"
    prefix:   /component

SinettMLABBuilderBundle_group:
    resource: "@SinettMLABBuilderBundle/Resources/config/routing/group.yml"
    prefix:   /group

SinettMLABBuilderBundle_help:
    resource: "@SinettMLABBuilderBundle/Resources/config/routing/help.yml"
    prefix:   /help

SinettMLABBuilderBundle_menu:
    resource: "@SinettMLABBuilderBundle/Resources/config/routing/menu.yml"
    prefix:   /menu

SinettMLABBuilderBundle_services:
    resource: "@SinettMLABBuilderBundle/Resources/config/routing/services.yml"
    prefix:   /services

SinettMLABBuilderBundle_template:
    resource: "@SinettMLABBuilderBundle/Resources/config/routing/template.yml"
    prefix:   /template
    
SinettMLABBuilderBundle_tracking:
    resource: "@SinettMLABBuilderBundle/Resources/config/routing/tracking.yml"
    prefix:   /tracking

SinettMLABBuilderBundle_user:
    resource: "@SinettMLABBuilderBundle/Resources/config/routing/user.yml"
    prefix:   /user

SinettMLABBuilderBundle_componentgroup:
    resource: "@SinettMLABBuilderBundle/Resources/config/routing/componentgroup.yml"
    prefix:   /componentgroup

admin_apps:
    path:   /admin/apps
    defaults: { _controller: SinettMLABBuilderBundle:Admin:apps }

admin_users:
    path:   /admin/users
    defaults: { _controller: SinettMLABBuilderBundle:Admin:users }

system:
    path:   /system/
    defaults: { _controller: SinettMLABBuilderBundle:Admin:system }

index:
    path: /index
    defaults: { _controller: SinettMLABBuilderBundle:System:index }

# compiler API related URLS (callbacks from API). These use "traditional" paremetr like ?x=y, so have no params specified here
cb_cmp_created_app:
    path: /callback/csAppCreated/
    defaults: { _controller: SinettMLABBuilderBundle:Services:cbCmpCreatedApp }
    
cb_cmp_verified_app:
    path: /callback/csAppVerified/
    defaults: { _controller: SinettMLABBuilderBundle:Services:cbCmpVerifiedApp }

cb_cmp_compiled_app:
    path: /callback/csAppCompiled/
    defaults: { _controller: SinettMLABBuilderBundle:Services:cbCmpCompiledApp }
    
