parameters:
#    sinett_mlab_builder.example.class: Sinett\MLAB\BuilderBundle\Example

services:
#    sinett_mlab_builder.example:
#        class: %sinett_mlab_builder.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
