parameters:
    sinett_mlab_builder.file_management.class: Sinett\MLAB\BuilderBundle\FileManagement\FileManagement

services:
    file_management:
        class:        "%sinett_mlab_builder.file_management.class%"
        arguments:    ["%mlab%"]

    update_default:
        class: Sinett\MLAB\BuilderBundle\Listener\EventListener
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }