# @copyright Copyright (c) 2013-2016, Norwegian Defence Research Establishment (FFI) - All Rights Reserved
# @license Proprietary and confidential
# @author Arild Bergh/Sinett 3.0 programme (firstname.lastname@ffi.no)
# 
# Unauthorized copying of this file, via any medium is strictly prohibited 
# 
# For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.
parameters:
    sinett_mlab_builder.file_management.class: Sinett\MLAB\BuilderBundle\FileManagement\FileManagement

services:
    file_management:
        class:        "%sinett_mlab_builder.file_management.class%"
        arguments:    ["%mlab%", "%mlab_app%", '@router', '@doctrine.orm.entity_manager', '%locale%']
#        scope: request

    update_default:
        class: Sinett\MLAB\BuilderBundle\Listener\EventListener
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }