# src/Sinett/MLAB/BuilderBundle/Resources/config/validation.yml

Sinett\MLAB\BuilderBundle\Entity\App:
    properties:
        zip_file:
            - File:
                maxSize: 100M
                maxSizeMessage: Maximum size for upload is 100MB
                mimeTypes: application/zip
                mimeTypesMessage: You can only upload ZIP files for apps
                
Sinett\MLAB\BuilderBundle\Entity\Component:
    properties:
        zip_file:
            - File:
                maxSize: 10M
                maxSizeMessage: Maximum size for upload is 10MB
                mimeTypes: application/zip
                mimeTypesMessage: You can only upload ZIP files for components
                
Sinett\MLAB\BuilderBundle\Entity\Template:
    properties:
        zip_file:
            - File:
                maxSize: 5M
                maxSizeMessage: Maximum size for upload is 5MB
                mimeTypes: application/zip
                mimeTypesMessage: You can only upload ZIP files for templates
                
                