# src/Sinett/MLAB/BuilderBundle/Resources/config/validation.yml

# @copyright Copyright (c) 2013-2016, Norwegian Defence Research Establishment (FFI) - All Rights Reserved
# @license Proprietary and confidential
# @author Arild Bergh/Sinett 3.0 programme (firstname.lastname@ffi.no)
# 
# Unauthorized copying of this file, via any medium is strictly prohibited 
# 
# For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.

Sinett\MLAB\BuilderBundle\Entity\App:
    properties:
        zip_file:
            - File:
                maxSize: 100M
                maxSizeMessage: Maximum size for upload is 100MB
                mimeTypes: application/zip
                mimeTypesMessage: You can only upload ZIP files for apps
                
Sinett\MLAB\BuilderBundle\Entity\Component:
    properties:
        zip_file:
            - File:
                maxSize: 20M
                maxSizeMessage: Maximum size for upload is 20MB
                mimeTypes: application/zip
                mimeTypesMessage: You can only upload ZIP files for components
                
Sinett\MLAB\BuilderBundle\Entity\Template:
    properties:
        zip_file:
            - File:
                maxSize: 20M
                maxSizeMessage: Maximum size for upload is 20MB
                mimeTypes: application/zip
                mimeTypesMessage: You can only upload ZIP files for templates
                
                