# @copyright Copyright (c) 2013-2016, Norwegian Defence Research Establishment (FFI) - All Rights Reserved
# @license Proprietary and confidential
# @author Arild Bergh/Sinett 3.0 programme (firstname.lastname@ffi.no)
# 
# Unauthorized copying of this file, via any medium is strictly prohibited 
# 
# For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.

# core table, the list of apps that is being developed, it is NOT linked to market,
# the apps table there is updated when new apps are updated  
Sinett\MLAB\BuilderBundle\Entity\App:
  type: entity
  table: app
  repositoryClass: Sinett\MLAB\BuilderBundle\Entity\AppRepository
  indexes:
    name_index:
      columns: [ name ]
    path_index:
      columns: [ path ]
    active_version_index:
      columns: [ active_version ]
    created_index:
      columns: [ created ]
    updated_index:
      columns: [ updated ]
    updatedby_id_index:
      columns: [ updatedby_id ]
    template_id_index:
      columns: [ template_id ]
    user_id_index:
      columns: [ user_id ]
    enabled_index:
      columns: [ enabled ]
    uid_index:
      columns: [ uid ]

  id:
    id: 
      type: integer
      generator:
          strategy: AUTO

  fields:
      name:
          type: string
          length: 255
          fixed: false
          nullable: false

      path:
          type: string
          length: 255
          fixed: false
          nullable: true
          
      description:
          type: text
          nullable: false

      keywords:
          type: text
          nullable: true

      active_version:
          type: float
          nullable: true
          options:
            default: 1

      enabled:
          type: boolean
          nullable: true
          options:
            default: true
            
      published:
          type: integer
          nullable: true
          options:
            default: 0
            
      created:
        type: date
        gedmo:
          timestampable:
            on: create
    
      updated:
        type: datetime
        gedmo:
          timestampable:
            on: update
            
      uid:
          type: text
          nullable: false
          
      tags:
          type: text
          nullable: true


#      templateId:
#        type: integer
#        unsigned: false
#        nullable: false
#        column: template_id
#          
#      userId:
#        type: integer
#        unsigned: false
#        nullable: false
#        column: user_id


#the categories for this apps
          
  manyToOne:
    template:
      targetEntity: Template
      inversedBy: apps

    user:
      targetEntity: User
      inversedBy: apps
          
    updatedBy:
      targetEntity: Sinett\MLAB\BuilderBundle\Entity\User
      inversedBy: appsUpdatedBy
      joinColumn:
        name: updatedby_id
        referencedColumnName: id
        
  manyToMany:
    groups:
      targetEntity: Group
      inversedBy: apps
      joinTable:
        name: apps_groups
        joinColumns:
          app_id:
            referencedColumnName: id
        inverseJoinColumns:
          group_id:
            referencedColumnName: id

# link to versions for this app
  oneToMany:
    appVersions:
      targetEntity: AppVersion
      mappedBy: app
      cascade: [persist]
    
  lifecycleCallbacks: {  }
