# list of categorieds that wil be used to classify all apps.
# it is also used to categoriese users, this is simply used to provide default categories for new apps they create 
# this will support three levels, top = branch, mid = job area, bottom = anything.
# it is a simple tree with parent_id pointing to id in same table

Sinett\MLAB\BuilderBundle\Entity\Category:
  type: entity
  table: category
  repositoryClass: Sinett\MLAB\BuilderBundle\Entity\CategoryRepository
  indexes:
    name_index:
      columns: [ name ]
  
  id:
    id: 
      type: integer
      generator:
          strategy: AUTO
  
  fields:
      name:
          type: string
          length: 255
          fixed: false
          nullable: false

      system:
          type: boolean
          nullable: false
          options:
            default: false
            
  oneToMany:
    children:
      targetEntity: Category
      mappedBy: parent
  
  manyToOne:
    parent:
      targetEntity: Category
      inversedBy: children
      
  lifecycleCallbacks: {  }
