# @copyright Copyright (c) 2013-2016, Norwegian Defence Research Establishment (FFI) - All Rights Reserved
# @license Proprietary and confidential
# @author Arild Bergh/Sinett 3.0 programme (firstname.lastname@ffi.no)
# 
# Unauthorized copying of this file, via any medium is strictly prohibited 
# 
# For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.

# list of categories that will be used to classify all apps.
# it is also used to categorise users, this is simply used to provide default categories for new apps they create 
# this will support three levels, top = branch, mid = job area, bottom = anything.
# it is a simple tree with parent_id pointing to id in same table
# Uses Gedmo extension to provide tree functionality

Sinett\MLAB\BuilderBundle\Entity\Category:
  type: entity
  table: category
  repositoryClass: Gedmo\Tree\Entity\Repository\NestedTreeRepository
  gedmo:
    tree:
      type: nested
  indexes:
    name_index:
      columns: [ name ]
    enabled_index:
      columns: [ enabled ]
  
  id:
    id: 
      type: integer
      generator:
          strategy: AUTO
  
  fields:
      name:
          type: string
          length: 255
          fixed: false
          nullable: false

      system:
          type: boolean
          nullable: true
          options:
            default: false
            
      enabled:
          type: boolean
          nullable: true
          options:
            default: true
            
      lft:
        type: integer
        gedmo:
          - treeLeft
          
      rgt:
        type: integer
        gedmo:
          - treeRight
          
      root:
        type: integer
        nullable: true
        gedmo:
          - treeRoot
          
      lvl:
        type: integer
        gedmo:
          - treeLevel
          
  manyToOne:
    parent:
      targetEntity: Sinett\MLAB\BuilderBundle\Entity\Category
      inversedBy: children
      joinColumn:
        name: parent_id
        referencedColumnName: id
        onDelete: CASCADE
      gedmo:
        - treeParent
        
  oneToMany:
    children:
      targetEntity: Sinett\MLAB\BuilderBundle\Entity\Category
      mappedBy: parent
      orderBy:
        lft: ASC
        
    appsCategory1:
      targetEntity: App
      mappedBy: category
      joinColumn:
        name: id
        referencedColumnName: category_1

    appsCategory2:
      targetEntity: App
      mappedBy: category
      joinColumn:
        name: id
        referencedColumnName: category_2
        
    appsCategory3:
      targetEntity: App
      mappedBy: category
      joinColumn:
        name: id
        referencedColumnName: category_3

    usersCategory1:
      targetEntity: User
      mappedBy: category
      joinColumn:
        name: id
        referencedColumnName: category_1

    usersCategory2:
      targetEntity: User
      mappedBy: category
      joinColumn:
        name: id
        referencedColumnName: category_2
        
    usersCategory3:
      targetEntity: User
      mappedBy: category
      joinColumn:
        name: id
        referencedColumnName: category_3

  lifecycleCallbacks: {  }
