# @copyright Copyright (c) 2013-2020, Norwegian Defence Research Establishment (FFI)
# @license Licensed under the Apache License, Version 2.0 (For the full copyright and license information, please view the /LICENSE_MLAB file that was distributed with this source code)
# @author Cecilie Jackbo Gran/Sinett 3.0 programme (firstname.middlename.lastname@ffi.no)
# 
 
# For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.
Sinett\MLAB\BuilderBundle\Entity\ComponentGroup:
  type: entity
  table: components_groups
  repositoryClass: Sinett\MLAB\BuilderBundle\Entity\ComponentGroupRepository
  
  indexes:
    component_index:
      columns: [ component_id ]
    group_index:
      columns: [ group_id ]
    access_state_index:
      columns: [ access_state ]

  id:
    id: 
      type: integer
      generator:
          strategy: AUTO

  fields:
    credential:
      type: text
      nullable: true
         
    access_state:
      type: integer
      nullable: false
      options:
        default: 0
         
# link to apps for a version
  manyToOne:
    component:
      targetEntity: Component
      inversedBy: componentGroups
      joinColumn:
        name: component_id
        referencedColumnName: id
        
    group:
      targetEntity: Group
      inversedBy: componentGroups
      joinColumn:
        name: group_id
        referencedColumnName: id
      
