# @copyright Copyright (c) 2013-2016, Norwegian Defence Research Establishment (FFI) - All Rights Reserved
# @license Proprietary and confidential
# @author Arild Bergh/Sinett 3.0 programme (firstname.lastname@ffi.no)
# @author Cecilie Jackbo Gran/Sinett 3.0 programme (firstname.middlename.lastname@ffi.no)
# 
# Unauthorized copying of this file, via any medium is strictly prohibited 
# 
# For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.
Sinett\MLAB\BuilderBundle\Entity\Group:
  type: entity
  table: grp
  repositoryClass: Sinett\MLAB\BuilderBundle\Entity\GroupRepository
  indexes:
    name_index:
      columns: [ name ]
    is_default_index:
      columns: [ is_default ]
    enabled_index:
      columns: [ enabled ]

  id:
    id: 
      type: integer
      generator:
          strategy: AUTO

  fields:
#removed for Symfony_2.8, create duplicate column issue
#    name:
#      type: string
#      length: 255
#      fixed: false
#      nullable: false

    description:
      type: text
      nullable: true

    isDefault:
      type: boolean
      nullable: true
      column: is_default
      options:
        default: false

    enabled:
      type: boolean
      nullable: true
      options:
        default: true
            
    categories:
      type: text
      nullable: true

                          
  manyToMany:
    users:
      targetEntity: User
      mappedBy: groups
      cascade: [persist]

    apps:
      targetEntity: App
      mappedBy: groups      
      
    templates:
      targetEntity: Template
      mappedBy: groups      
      
#    components:
#      targetEntity: Component
#      mappedBy: groups      

  oneToMany:
    componentGroups:
      targetEntity: ComponentGroup
      mappedBy: group
      cascade: [persist]