# @copyright Copyright (c) 2013-2016, Norwegian Defence Research Establishment (FFI) - All Rights Reserved
# @license Proprietary and confidential
# @author Arild Bergh/Sinett 3.0 programme (firstname.lastname@ffi.no)
# 
# Unauthorized copying of this file, via any medium is strictly prohibited 
# 
# For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.

Sinett\MLAB\BuilderBundle\Entity\Menu:
  type: entity
  table: menu
  repositoryClass: Sinett\MLAB\BuilderBundle\Entity\MenuRepository
  indexes:
    parent_id_index:
      columns: [ parent_id ]
    order_by_index:
      columns: [ order_by ]
    filter_url_index:
      columns: [ filter_url ]
    filter_role_index:
      columns: [ filter_role ]

  id:
    id: 
      type: integer
      generator:
          strategy: AUTO

  fields:
#link to parent, blank if top level
    parentId:
      type: integer
      unsigned: false
      nullable: false
      column: parent_id

    orderBy:
      type: integer
      unsigned: false
      nullable: false
      column: order_by

# what to display in the menu
    contentHtml:
      type: text
      nullable: true
      column: content_html
      
    contentPhp:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: content_php
      
    class:
      type: string
      length: 255
      fixed: false
      nullable: true
      
    help:
      type: text
      nullable: true
        
# fields that (together with link to groups) limit who gets a menu      
    filterRole:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: filter_role

    filterUrl:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: filter_url
        
# destination / javascript
    url:
      type: text
      nullable: true
      
