# @copyright Copyright (c) 2013-2020, Norwegian Defence Research Establishment (FFI)
# @license Licensed under the Apache License, Version 2.0 (For the full copyright and license information, please view the /LICENSE_MLAB file that was distributed with this source code)
# @author Arild Bergh/Sinett 3.0 programme (firstname.lastname@ffi.no)
# 
 
# For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.
Sinett\MLAB\BuilderBundle\Entity\TemplateGroupData:
  type: entity
  table: templates_groups_data
  repositoryClass: Sinett\MLAB\BuilderBundle\Entity\TemplateGroupDataRepository
  
  indexes:
    template_index:
      columns: [ template_id ]
    group_index:
      columns: [ group_id ]
    access_state_index:
      columns: [ access_state ]

  id:
    id: 
      type: integer
      generator:
          strategy: AUTO

  fields:
    template_id:
      type: integer
      nullable: false
      options:
        default: 0
         
    group_id:
      type: integer
      nullable: false
      options:
        default: 0
         
    access_state:
      type: integer
      nullable: false
      options:
        default: 0
  manyToOne:
    template:
      targetEntity: Template
      inversedBy: templateGroups
      joinColumn:
        name: template_id
        referencedColumnName: id
        
    group:
      targetEntity: Group
      inversedBy: templateGroups
      joinColumn:
        name: group_id
        referencedColumnName: id
      
