# user details, uses FosUserbundle for management
Sinett\MLAB\BuilderBundle\Entity\User:
  type: entity
  table: usr
  repositoryClass: Sinett\MLAB\BuilderBundle\Entity\UserRepository
  indexes:
    username_index:
      columns: [ username ]
    email_index:
      columns: [ email ]
    password_index:
      columns: [ password ]
    created_index:
      columns: [ created ]
    updated_index:
      columns: [ updated ]
  
  id:
    id: 
      type: integer
      generator:
          strategy: AUTO

  fields:
    created:
      type: date
      gedmo:
        timestampable:
          on: create
    
    updated:
      type: datetime
      gedmo:
        timestampable:
          on: update
    
    locale:
      type: string
      length: 6
      fixed: false
      nullable: true

#the branch they belong to, if any, used to define categories for apps
          
  manyToOne:
    categoryOne:
      targetEntity: Category
      joinColumn:
        name: category_1
        referencedColumnName: id

    categoryTwo:
      targetEntity: Category
      joinColumn:
        name: category_2
        referencedColumnName: id

    categoryThree:
      targetEntity: Category
      joinColumn:
        name: category_3
        referencedColumnName: id
        
  oneToMany:
    apps:
      targetEntity: App
      mappedBy: user

    appsUpdatedBy:
      targetEntity: App
      mappedBy: user
      joinColumn:
        name: id
        referencedColumnName: updateby_id

  manyToMany:
    groups:
      targetEntity: Group
      inversedBy: users
      joinTable:
        name: users_groups
        joinColumns:
          user_id:
            referencedColumnName: id
        inverseJoinColumns:
          group_id:
            referencedColumnName: id
      cascade: [persist]
      
  lifecycleCallbacks: {  }
