<?php

namespace Sinett\MLAB\BuilderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppRepository extends EntityRepository
{

	/**
	 * Returns a list of all apps that is allowed for the specified groups
	 * @param collection of Sinett\MLAB\BuilderBundle\Entity\Group $groups
	 */
	public function findAllByGroups ( $groups) {
		$apps = array();
		foreach ($groups as $group) {
			$temp_apps = $group->getApps();
			foreach ($temp_apps as $temp_app) {
                $temp_app->getAppVersions();
				$apps[$temp_app->getId()] = $temp_app->getArray();
			}
		}
		return $apps;
	}
    
  	/**
	 * Returns an array of *paths* of all components that is allowed for the specified groups
	 * This path = the internal component type/name which = the folder name of the component
	 * @param collection of Sinett\MLAB\BuilderBundle\Entity\Group $groups
	 */
	public function checkAccessByGroups ( $app_id, $groups ) {
        foreach ($groups as $group) {
			$temp_apps = $group->getApps();
			foreach ($temp_apps as $temp_app) {
                if ($temp_app->getEnabled() && $temp_app->getId() == $app_id) {
                    return true;
                }
			}
		}
		return false;
	}
	
}
