<?php

namespace Sinett\MLAB\BuilderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppRepository extends EntityRepository
{

	/**
	 * Returns a list of all apps that the current user is allowed to see through their group memberships
	 * @param unknown $user
	 */
	public function findAllForCurrentUser(Sinett\MLAB\BuilderBundle\Entity\User $user) {
		$groups = $user->getGroups();
		die(print_r($groups, true));
	} 
}
