<?php

namespace Sinett\MLAB\BuilderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
	
	/**
     * Load all categories for a certain parent at a certain level
	 * @param unknown $role
	 */
	public function loadChildrenByLevel($id, $level) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('c')
            ->from($this->getEntityName(), 'c')
            ->where('c.parent = ' . $id)
            ->andWhere('c.lvl = ' . $level);
        return $qb->getQuery()->getResult();
	}
}
