<?php
/*******************************************************************************************************************************
@copyright Copyright (c) 2013-2016, Norwegian Defence Research Establishment (FFI) - All Rights Reserved
@license Proprietary and confidential
@author Arild Bergh/Sinett 3.0 programme (firstname.lastname@ffi.no)

Unauthorized copying of this file, via any medium is strictly prohibited

For the full copyright and license information, please view the LICENSE_MLAB file that was distributed with this source code.
*******************************************************************************************************************************/

namespace Sinett\MLAB\BuilderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository
{
	
	/**
	 * Retrieves different records for admin and super admin users. For admin it only shows groups that they themselves have been assigned to
     * This way we can properly use the admin role to manage parts of an organisation
	 * @param string $role
	 * @param array $groups
	 */
	public function findByRoleAndGroup($role, $groups) {
		if ($role == "ROLE_SUPER_ADMIN") {
			return $this->findAll();
			
		} else if ($role == "ROLE_ADMIN") {
			$qb = $this->getEntityManager()->createQueryBuilder();
    		$qb->select(array('g'))
	            ->from($this->getEntityName(), 'g')
                ->where($qb->expr()->in('g.name',$groups));
    		return $qb->getQuery()->getResult();
		} 
	}

	
}
