<?php

namespace Sinett\MLAB\BuilderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
	/**
	 * Builds a query based on the users roles and groups + current URL and returns all the menus they should see 
	 * 
	 * @param unknown $user: Current user, use role and groups from this to determine what the can see
	 * @param unknown $url: Current URL used to filter against
	 * @return array of menu items
	 */
	public function findMenuItems($user, $filter_url, $role_hierarchy) {
		$roles = $menus = array();

//roles can contain roles that contain roles, pick up top level first, then loop through to get rest
		$user_role = $user->getRoles()[0];
		$roles[] = $user_role;
		$roles = array_merge($roles, $role_hierarchy[$user_role]);
		
//this loop picks up all sub-roles that a role covers 
		foreach ($role_hierarchy[$user_role] as $sub_role) {
			if (isset($role_hierarchy[$sub_role])) {
				$roles = array_merge($roles, $role_hierarchy[$sub_role]);
			}
		}
		$filter_roles = implode(",", $roles);

		$sql = "SELECT m FROM SinettMLABBuilderBundle:Menu AS m
		WHERE m.parentId = 0
		AND (COALESCE(m.filterUrl, '') = '' OR m.filterUrl LIKE '{$filter_url}%')
		AND (COALESCE(m.filterRole, '') = '' OR m.filterRole IN('{$filter_roles}'))
		ORDER BY m.orderBy";
		
		$top_menus = $this->getEntityManager()->createQuery($sql)->getArrayResult();

		foreach ($top_menus as $menu_item) {
			if (isset($menu_item["contentPhp"]) && !empty($menu_item["contentPhp"])) {
				$menu_item["contentHtml"] = eval("return " . $menu_item["contentPhp"]);
			}
				
			$menu_item["help"] = htmlspecialchars($menu_item["help"]);
				
			$sql = "SELECT m FROM SinettMLABBuilderBundle:Menu AS m
					WHERE m.parentId = {$menu_item["id"]}
					AND (COALESCE(m.filterUrl, '') = '' OR m.filterUrl LIKE '{$filter_url}%')
					AND (COALESCE(m.filterRole, '') = '' OR m.filterRole IN('{$filter_roles}'))
					ORDER BY m.orderBy";
			
			$sub_menus = $this->getEntityManager()->createQuery($sql)->getArrayResult();
				
			$menu_item["children"] = array();
			foreach ($sub_menus as $sub_row) {
				$menu_subitem = (array) $sub_row;
				if (isset($menu_subitem["contentPhp"]) && !empty($menu_subitem["contentPhp"])) {
					$menu_subitem["contentHtml"] = eval("return " . $menu_subitem["contentPhp"]);
				}
					
				$menu_subitem["help"] = htmlspecialchars($menu_subitem["help"]);
				$menu_item["children"][] = $menu_subitem;
			}
				
			$menus[] = $menu_item;
				
		}
		
		return $menus;
			
	}


	public function findMenuItemsRaw() {
	
		$menus = array();
	
		$sql = "SELECT m FROM SinettMLABBuilderBundle:Menu AS m
				WHERE m.parentId = 0
				ORDER BY m.orderBy";
	
		$menus = $this->getEntityManager()->createQuery($sql)->getArrayResult();
	
		foreach ($menus as $id => $menu_item) {

			$sql = "SELECT m FROM SinettMLABBuilderBundle:Menu AS m
					WHERE m.parentId = {$menu_item["id"]}
					ORDER BY m.orderBy";
				
			$menus[$id]["children"] = $this->getEntityManager()->createQuery($sql)->getArrayResult();
		}	
		
		return $menus;
				
	}
	
	
}
