<?php

namespace Sinett\MLAB\BuilderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateRepository extends EntityRepository
{
	/**
	 * Returns a list of all templates that is allowed for the specified groups
	 * @param collection of Sinett\MLAB\BuilderBundle\Entity\Group $groups
	 */
	public function findAllByGroups ( $groups) {
		$templates = array();
		foreach ($groups as $group) {
			$temp_templates = $group->getTemplates();
			foreach ($temp_templates as $temp_template) {
				$templates[$temp_template->getId()] = $temp_template->getArray();
			}
		}
		return $templates;
	}
    
	/**
	 * Returns a list of all templates with information about whether they can be deleted (not used in any apps)
	 * @param collection of Sinett\MLAB\BuilderBundle\Entity\Group $groups
	 */
	public function findAllCheckDeleteable () {
		$templates = $this->findAll();
		foreach ($templates as $id => $template) {
			$temp_apps = $template->getApps();
			$templates[$id]->setCanDelete($temp_apps->count() == 0);
		}
		return $templates;
	}
    
	
	
}
